accounts:
  - name: alice
    coins: ["200000000uheart"]
  - name: bob
    coins: ["100000000uheart"]
validator:
  name: alice
  staked: "100000000uheart"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5uheart"]
genesis:
  app_state:
    bank:
      denom_metadata:
        - description: "The gas token of AI"
          display: "heart"
          base: "uheart"
          name: "HeartToken"
          symbol: "HEART"
          denom_units:
            - denom: "uheart"
              aliases:
                - "milliheart"
              exponent: "0"
            - denom: "mheart"
              aliases:
                - "microheart"
              exponent: "3"
            - denom: "heart"
              exponent: "6"
    staking:
      params:
        bond_denom: "uheart"
