version: 1
build:
  proto:
    path: proto
    third_party_paths:
      - third_party/proto
      - proto_vendor
accounts:
  - name: alice
    coins:
      - 200000000uheart
  - name: bob
    coins:
      - 100000000uheart
faucet:
  name: bob
  coins:
    - 5uheart
  host: 0.0.0.0:4500
genesis:
  app_state:
    bank:
      denom_metadata:
        - base: uheart
          denom_units:
            - aliases:
                - milliheart
              denom: uheart
              exponent: "0"
            - aliases:
                - microheart
              denom: mheart
              exponent: "3"
            - denom: heart
              exponent: "6"
          description: The gas token of AI
          display: heart
          name: HeartToken
          symbol: HEART
    staking:
      params:
        bond_denom: uheart
validators:
  - name: alice
    bonded: 100000000uheart
  - name: bob
    bonded: 100000000uheart
